title: Fortify Engineering
email: 
description: > # this means to ignore newlines until "baseurl:"
  Fortify Engineering Github repositories
future: true

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fortify.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#host: https://pages.github.hpe.com/eran-argaman

### content configuration ###
title:       "Fortify Engineering Github Repositiries"
keywords:    "Fortify, Security"
description: "Fortify Engineering Github Repositiries"
source_link: ""
highlighter: rouge

kramdown:
  auto_ids:  false
